import { expect, test } from "@playwright/test";

const MB = 1024 * 1024;

test("clear clutter: AI-made things and your uploads are cleared separately, after a preview and a confirmation", async ({ page }) => {
  const calls: { dry_run: boolean; since: number | null; until: number | null; categories: string[] }[] = [];
  await page.route("**/api/cleanup", async (r) => {
    const b = r.request().postDataJSON();
    calls.push(b);
    const cats = Object.fromEntries(b.categories.map((c: string) => [c, { count: 2, bytes: 5 * MB }]));
    await r.fulfill({ json: { categories: cats, total_bytes: 5 * MB * b.categories.length, cleared: !b.dry_run } });
  });
  await page.goto("/settings/storage");
  const ai = page.getByRole("region", { name: "Generated by AI" });
  const mine = page.getByRole("region", { name: "Your uploads" });
  await expect(page.getByTestId("ai-summary")).toHaveText("8 items, about 20 MB.");
  await expect(page.getByTestId("uploads-summary")).toHaveText("8 items, about 20 MB.");

  // Uploads: only photos, from a date range.
  for (const label of ["Videos", "Documents and other files", "Voice messages"]) await mine.getByLabel(`Your uploads: ${label}`).uncheck();
  await expect(page.getByTestId("uploads-summary")).toHaveText("2 items, about 5.0 MB.");
  await mine.getByLabel("Date range").check();
  await mine.getByLabel("From", { exact: true }).fill("2026-09-01");
  await mine.getByLabel("To", { exact: true }).fill("2026-09-30");
  await expect.poll(() => calls.at(-1)?.since ?? null).not.toBeNull();
  expect(calls.at(-1)!.until! - calls.at(-1)!.since!).toBe(30 * 86400);          // "to" includes that whole day

  await mine.getByRole("button", { name: "Clear", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toContainText("can't be undone");
  await dialog.getByRole("button", { name: /^Clear 5\.0 MB/ }).click();
  await expect.poll(() => calls.filter((c) => !c.dry_run).length).toBe(1);
  expect(calls.find((c) => !c.dry_run)!.categories).toEqual(["my_photos"]);        // the AI group is untouched

  // The AI group clears on its own, everything by default.
  await ai.getByRole("button", { name: "Clear", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: /^Clear 20 MB/ }).click();
  await expect.poll(() => calls.filter((c) => !c.dry_run).length).toBe(2);
  const aiClear = calls.filter((c) => !c.dry_run)[1];
  expect(aiClear.categories).toEqual(["videos", "files", "artifacts", "temp"]);
  expect(aiClear.since).toBeNull();
});

test("check for updates is greyed out, with the reason, while web access is off", async ({ page }) => {
  await page.route("**/api/capabilities", async (r) => {
    const j = await (await r.fetch()).json();
    await r.fulfill({ json: { ...j, web_access: false } });
  });
  await page.goto("/settings/updates");
  await expect(page.getByRole("button", { name: "Check for updates" })).toBeDisabled();
  await expect(page.getByText("Web access is off, so the app doesn't go online.")).toBeVisible();
});
