"""Settings → Clear clutter, in two groups, each for everything or a date range:
  * Generated by AI: videos, images and files it made, mini apps and diagrams, temporary files;
  * Your uploads: photos and screenshots, videos, documents and other files, voice messages.
The text of chats is never touched, and files added to a Project stay (projects depend on them).

Cleared attachments keep their row (with an empty path) so chats can say "cleared" instead of
breaking; cleared mini apps are deleted with their versions.
"""

from __future__ import annotations

import contextlib
import shutil
import time
from pathlib import Path

from orchestrator.storage.store import Store

# Attachment categories: SQL conditions on the attachments table.
_NOT_PROJECT = "id NOT IN (SELECT attachment_id FROM project_files)"
ATTACHMENTS = {
    "videos": "source = 'tool' AND COALESCE(kind,'') = 'video'",
    "files": "source = 'tool' AND COALESCE(kind,'') != 'video'",
    "my_photos": "source != 'tool' AND kind IN ('image', 'screenshot')",
    "my_videos": "source != 'tool' AND kind = 'video'",
    "my_voice": "source != 'tool' AND (source = 'voice_message' OR kind = 'audio')",
    "my_files": "source != 'tool' AND source != 'voice_message' AND COALESCE(kind,'') NOT IN "
                "('image', 'screenshot', 'video', 'audio')",
}
CATEGORIES = (*ATTACHMENTS, "artifacts", "temp")
RECENT_S = 10 * 60          # temporary files touched in the last 10 minutes may be in use (a render)


def _range(col: str, since: float | None, until: float | None) -> tuple[str, list]:
    sql, params = [], []
    if since is not None:
        sql.append(f"{col} >= ?")
        params.append(since)
    if until is not None:
        sql.append(f"{col} < ?")
        params.append(until)
    return (" AND " + " AND ".join(sql)) if sql else "", params


def _size(p: Path) -> int:
    try:
        if p.is_dir():
            return sum(f.stat().st_size for f in p.rglob("*") if f.is_file())
        return p.stat().st_size
    except OSError:
        return 0


def _temp_entries(data_dir: Path, since: float | None, until: float | None) -> list[Path]:
    """Top-level items in tmp/ (except incognito, which belongs to open chats) and cache/."""
    now = time.time()
    out = []
    for root in (data_dir / "tmp", data_dir / "cache"):
        if not root.is_dir():
            continue
        for p in root.iterdir():
            if p.name == "incognito":
                continue
            items = [p] if p.is_file() else [c for c in p.iterdir()] if p.name in ("sandbox", "video") else [p]
            for item in items:
                try:
                    mtime = item.stat().st_mtime
                except OSError:
                    continue
                if now - mtime < RECENT_S:
                    continue
                if (since is None or mtime >= since) and (until is None or mtime < until):
                    out.append(item)
    return out


async def _attachments(store: Store, category: str, since, until) -> list[dict]:
    where, params = _range("created_at", since, until)
    return await store.db.all(
        f"SELECT id, path, size, sha256 FROM attachments WHERE path != '' AND {_NOT_PROJECT} "
        f"AND ({ATTACHMENTS[category]}){where}", tuple(params))


async def _artifacts(store: Store, since, until) -> list[dict]:
    where, params = _range("a.updated_at", since, until)
    return await store.db.all(
        "SELECT a.id, COALESCE(SUM(LENGTH(v.content)), 0) AS size FROM artifacts a "
        f"LEFT JOIN artifact_versions v ON v.artifact_id = a.id WHERE 1=1{where} GROUP BY a.id", tuple(params))


async def run(store: Store, data_dir: Path, categories: list[str], since: float | None = None,
              until: float | None = None, dry_run: bool = True) -> dict:
    """Count (dry_run) or clear. Returns {category: {count, bytes}} and the total."""
    cats = [c for c in categories if c in CATEGORIES]
    out: dict[str, dict] = {}
    for cat in cats:
        if cat in ATTACHMENTS:
            rows = await _attachments(store, cat, since, until)
            out[cat] = {"count": len(rows), "bytes": sum(r["size"] or 0 for r in rows)}
            if not dry_run:
                ids = {r["id"] for r in rows}
                for r in rows:
                    # Files are shared by content: keep it if anything we aren't clearing still uses it.
                    others = await store.db.all("SELECT id FROM attachments WHERE path=? AND path != ''", (r["path"],))
                    if all(o["id"] in ids for o in others):
                        Path(r["path"]).unlink(missing_ok=True)
                    await store.db.execute("UPDATE attachments SET path='', size=0 WHERE id=?", (r["id"],))
                    await store.delete_chunks("attachment", r["id"])
        elif cat == "artifacts":
            rows = await _artifacts(store, since, until)
            out[cat] = {"count": len(rows), "bytes": sum(r["size"] for r in rows)}
            if not dry_run:
                for r in rows:
                    await store.db.execute("DELETE FROM artifact_versions WHERE artifact_id=?", (r["id"],))
                    await store.db.execute("DELETE FROM artifacts WHERE id=?", (r["id"],))
                    await store.delete_chunks("artifact", r["id"])
        elif cat == "temp":
            items = _temp_entries(data_dir, since, until)
            out[cat] = {"count": len(items), "bytes": sum(_size(p) for p in items)}
            if not dry_run:
                for p in items:
                    if p.is_dir() and not p.is_symlink():
                        shutil.rmtree(p, ignore_errors=True)
                    else:
                        with contextlib.suppress(OSError):
                            p.unlink()
    return {"categories": out, "total_bytes": sum(v["bytes"] for v in out.values()), "cleared": not dry_run}
